language: node_js

node_js:
  - "10"
  - "12"
  - "13"
  - "14"

os:
  - linux
  - windows

script:
  - npm run lint && npm run typescript

notifications:
  email:
    on_success: never
    on_failure: always
